name: Run Job Shop Checker

on:
  workflow_dispatch:        # Manual trigger
  workflow_call:            # Reusable workflow support
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'     # Every 1 minute

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install selenium beautifulsoup4 twilio

      - name: Clean up any stale chromedriver in repo
        run: |
          find . -name 'chromedriver' -type f -delete || true

      - name: Install Chrome v135 and ChromeDriver v135 for Linux
        run: |
          # Install Chrome v135 for Linux (Testing channel)
          wget https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.42/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo mv chrome-linux64 /opt/chrome

          # Replace existing symlink if present
          sudo rm -f /usr/bin/google-chrome
          sudo ln -s /opt/chrome/chrome /usr/bin/google-chrome

          # Install matching ChromeDriver v135
          wget https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.42/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Run webscrap.py script
        env:
          LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
          ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          TWILIO_PHONE: ${{ secrets.TWILIO_PHONE }}
          YOUR_PHONE: ${{ secrets.YOUR_PHONE }}
        run: |
          python3 webscrap.py
