name: Run Job Shop Checker

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install selenium beautifulsoup4 twilio

    - name: Install specific Chrome & ChromeDriver versions
      run: |
        sudo apt update
        sudo apt install -y wget unzip

        # Install Chrome 113
        wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_113.0.5672.92-1_amd64.deb
        sudo apt install -y ./google-chrome-stable_113.0.5672.92-1_amd64.deb

        # Install ChromeDriver 113
        wget https://chromedriver.storage.googleapis.com/113.0.5672.63/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run script
      env:
        LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
        LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        TWILIO_PHONE: ${{ secrets.TWILIO_PHONE }}
        YOUR_PHONE: ${{ secrets.YOUR_PHONE }}
      run: |
        python3 webscrap.py
