name: Test Scheduler

on:
  schedule:
    - cron: '*/2 * * * *' # Every 2 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Log time
        run: 'echo "⏰ Hello! Time now: $(date -u)"'
